version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: master
  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: daily
    target-branch: master
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    target-branch: master
